<?php

/**
 * WP Wiki Template
 * 
 * @since 1.0.0
 */

namespace bf\wpPedia\modules;

// Make sure this file runs only from within WordPress.
defined( 'ABSPATH' ) or die();

class tooltip {

	private $excerpt_length = 40;

	public function __construct() {

		add_action( 'wp_ajax_nopriv_wppedia_generate_tooltip', [ $this, '__generate_tooltip' ] );
		add_action( 'wp_ajax_wppedia_generate_tooltip', [ $this, '__generate_tooltip' ] );

		// Add custom image size used in tooltips
		add_image_size( 'wppedia_tooltip_thumbnail', 320, 180, true );

	}

	function __generate_tooltip() {

		// The Post ID delivered through the AJAX request
		$post_id = $_POST['post_id'];

		$this->tooltip_thumbnail( $post_id );

		echo apply_filters( 'wppedia_tooltip_before_excerpt', '<div class="wppedia-tooltip-content">' );
		$this->the_excerpt( $post_id );
		echo apply_filters( 'wppedia_tooltip_after_excerpt', '</div>' );
		
		die;

	}

	/**
	 * Get the excerpt with fallback generated from the content
	 * 
	 * @param WP_Post|int $post - Post ID or object
	 * 
	 * @since 1.0.0
	 */
	private function get_the_excerpt( $post = null ) {

		$str = '';

		// setup Postdata
    $post = get_post( $post );
    if ( empty( $post ) )
      return;

		if ( ! has_excerpt( $post ) ) {

			// Get the Post Content (formatted)
			setup_postdata( $post );
			$str = get_the_content( null, false, $post );
			wp_reset_postdata( $post );

			// Check if Text is not empty
			if ( '' != $str && $str ) {

				// Add some filters to the text
				$str = strip_shortcodes( $str );
				$str = str_replace(']]&gt;', ']]&gt;', $str);

				// Get a formatted string
				$str = force_balance_tags( html_entity_decode( wp_trim_words( htmlentities( $str ), $this->excerpt_length, null ) ) );

			}

		} else {

			// If an excerpt was specified just add some p tags
			$str = wpautop( $post->post_excerpt );

		}

		return apply_filters( 'wppedia_tooltip_get_excerpt', $str );

	}

	/**
	 * Display the autogenerated excerpt
	 * 
	 * @param WP_Post|int $post - Post ID or object
	 * 
	 * @since 1.0.0
	 */
	private function the_excerpt( $post = null ) {

		echo apply_filters( 'wppedia_tooltip_excerpt', $this->get_the_excerpt( $post ) );

	}

	/**
	 * Display the post thumbnail
	 * 
	 * @param WP_Post|int $post - Post ID or object
	 * 
	 * @return boolean - true if an image is available
	 * 
	 * @since 1.0.0
	 */
	private function tooltip_thumbnail( $post = null ) {

    $post = get_post( $post );
    if ( empty( $post ) )
      return;

		if ( ! has_post_thumbnail( $post ) )
			return;

		$thumbnail_id = get_post_thumbnail_id( $post );
		
		echo wp_get_attachment_image( $thumbnail_id, 'wppedia_tooltip_thumbnail', [ 'class' => 'wppedia-tooltip-image' ] );

		return true;

	}

}
